---
# tasks file for ssh
- name: generate ssh key
  become: yes
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    force: no


- name: check ssh keys
  shell: cat ~/.ssh/"{{ ssh_key_filename }}"
  register: ssh_keys

- name: check keys
  debug: msg="{{ ssh_keys.stdout }}"

- name: fetch the ssh key
  ansible.builtin.fetch:
    src: ~/.ssh/id_rsa.pub
    dest: /Users/tomasrinblad/openstack/roles/ssh/files/{{ inventory_hostname }}
    flat: yes

- name: add ssh keys to host
# Change name after we fixed so only deploy SSH key is added to the file.
  ansible.builtin.lineinfile:
    path: /home/ubuntu/test
    line: "{{ item }}"
  with_file:
   - compute1
   - deploy