---
# tasks file for chrony
- name: make sure that chrony is installed
  become: yes
  ansible.builtin.apt:
    name: chrony
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: deploy chrony.conf template
  become: yes
  ansible.builtin.template:
    src: ../templates/chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: 
    - Restart Chronyd